#!/bin/bash
# @Function
# show count of TCP connection Stat.
#
# @author Ronak Dhoot (rdhoot at live dot com)

# added -p MacOS, because netstat needs -p tcp to get only tcp output.

uname | grep Darwin -q && option_for_mac="-ptcp"

netstat -tna $option_for_mac | awk 'NR > 2 {
    s[$NF]++
}

END {
    for(v in s) {
        printf "%-11s %s\n", v, s[v]
    }
}' | sort -nr -k2,2
